// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/models.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> initDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiInitDatabase(dbPath: dbPath);

Future<void> addBookmark({
  required MangaSource source,
  required String mangaId,
  required String title,
  required String thumbnail,
}) => RustLib.instance.api.crateApiAddBookmark(
  source: source,
  mangaId: mangaId,
  title: title,
  thumbnail: thumbnail,
);

Future<void> removeBookmark({
  required MangaSource source,
  required String mangaId,
}) => RustLib.instance.api.crateApiRemoveBookmark(
  source: source,
  mangaId: mangaId,
);

Future<bool> isBookmarked({
  required MangaSource source,
  required String mangaId,
}) =>
    RustLib.instance.api.crateApiIsBookmarked(source: source, mangaId: mangaId);

Future<List<BookmarkItem>> getBookmarks() =>
    RustLib.instance.api.crateApiGetBookmarks();

Future<void> saveHistory({
  required MangaSource source,
  required String mangaId,
  required String mangaTitle,
  required String chapterPath,
  required String chapterTitle,
  required String thumbnail,
  required int lastPage,
}) => RustLib.instance.api.crateApiSaveHistory(
  source: source,
  mangaId: mangaId,
  mangaTitle: mangaTitle,
  chapterPath: chapterPath,
  chapterTitle: chapterTitle,
  thumbnail: thumbnail,
  lastPage: lastPage,
);

Future<List<HistoryItem>> getHistory() =>
    RustLib.instance.api.crateApiGetHistory();

Future<void> clearHistory() => RustLib.instance.api.crateApiClearHistory();

Future<void> saveDownloadedChapter({required DownloadedChapter chapter}) =>
    RustLib.instance.api.crateApiSaveDownloadedChapter(chapter: chapter);

Future<List<DownloadedChapter>> getDownloadedChapters() =>
    RustLib.instance.api.crateApiGetDownloadedChapters();

Future<String> deleteDownloadedChapter({
  required MangaSource source,
  required String chapterId,
}) => RustLib.instance.api.crateApiDeleteDownloadedChapter(
  source: source,
  chapterId: chapterId,
);

Future<bool> isChapterDownloaded({
  required MangaSource source,
  required String chapterId,
}) => RustLib.instance.api.crateApiIsChapterDownloaded(
  source: source,
  chapterId: chapterId,
);

Future<List<MangaSummary>> getLatestManga({
  required MangaSource source,
  required int page,
}) => RustLib.instance.api.crateApiGetLatestManga(source: source, page: page);

Future<List<MangaSummary>> getMangaByGenre({
  required MangaSource source,
  required String genre,
  required int page,
}) => RustLib.instance.api.crateApiGetMangaByGenre(
  source: source,
  genre: genre,
  page: page,
);

Future<List<MangaSummary>> searchManga({
  required MangaSource source,
  required String query,
}) => RustLib.instance.api.crateApiSearchManga(source: source, query: query);

Future<MangaDetail> getMangaDetail({
  required MangaSource source,
  required String mangaId,
}) => RustLib.instance.api.crateApiGetMangaDetail(
  source: source,
  mangaId: mangaId,
);

Future<ChapterPages> getChapterPages({
  required MangaSource source,
  required String chapterPath,
}) => RustLib.instance.api.crateApiGetChapterPages(
  source: source,
  chapterPath: chapterPath,
);
