// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/db.dart';
import 'api/komikindo.dart';
import 'api/komiku.dart';
import 'api/models.dart';
import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitApp();
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1787296483;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_mangareader_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<ChapterPages> crateApiKomikindoKomikindoScraperGetChapterPages({
    required KomikindoScraper that,
    required String chapterPath,
  });

  Future<List<MangaSummary>> crateApiKomikindoKomikindoScraperGetLatestManga({
    required KomikindoScraper that,
    required int page,
  });

  Future<MangaDetail> crateApiKomikindoKomikindoScraperGetMangaDetail({
    required KomikindoScraper that,
    required String mangaId,
  });

  Future<KomikindoScraper> crateApiKomikindoKomikindoScraperNew();

  Future<List<MangaSummary>> crateApiKomikindoKomikindoScraperSearchManga({
    required KomikindoScraper that,
    required String query,
  });

  Future<ChapterPages> crateApiKomikuKomikuScraperGetChapterPages({
    required KomikuScraper that,
    required String chapterPath,
  });

  Future<List<MangaSummary>> crateApiKomikuKomikuScraperGetLatestManga({
    required KomikuScraper that,
    required int page,
  });

  Future<MangaDetail> crateApiKomikuKomikuScraperGetMangaDetail({
    required KomikuScraper that,
    required String mangaId,
  });

  Future<KomikuScraper> crateApiKomikuKomikuScraperNew();

  Future<List<MangaSummary>> crateApiKomikuKomikuScraperSearchManga({
    required KomikuScraper that,
    required String query,
  });

  Future<void> crateApiAddBookmark({
    required MangaSource source,
    required String mangaId,
    required String title,
    required String thumbnail,
  });

  Future<void> crateApiClearHistory();

  Future<void> crateApiDbDatabaseManagerAddBookmark({
    required MangaSource source,
    required String mangaId,
    required String title,
    required String thumbnail,
  });

  Future<void> crateApiDbDatabaseManagerClearHistory();

  Future<List<BookmarkItem>> crateApiDbDatabaseManagerGetBookmarks();

  Future<List<HistoryItem>> crateApiDbDatabaseManagerGetHistory();

  Future<void> crateApiDbDatabaseManagerInitDb({required String dbPath});

  Future<bool> crateApiDbDatabaseManagerIsBookmarked({
    required MangaSource source,
    required String mangaId,
  });

  Future<void> crateApiDbDatabaseManagerRemoveBookmark({
    required MangaSource source,
    required String mangaId,
  });

  Future<void> crateApiDbDatabaseManagerSaveHistory({
    required MangaSource source,
    required String mangaId,
    required String mangaTitle,
    required String chapterPath,
    required String chapterTitle,
    required String thumbnail,
    required int lastPage,
  });

  Future<List<BookmarkItem>> crateApiGetBookmarks();

  Future<ChapterPages> crateApiGetChapterPages({
    required MangaSource source,
    required String chapterPath,
  });

  Future<List<HistoryItem>> crateApiGetHistory();

  Future<List<MangaSummary>> crateApiGetLatestManga({
    required MangaSource source,
    required int page,
  });

  Future<MangaDetail> crateApiGetMangaDetail({
    required MangaSource source,
    required String mangaId,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiInitApp();

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiInitDatabase({required String dbPath});

  Future<bool> crateApiIsBookmarked({
    required MangaSource source,
    required String mangaId,
  });

  Future<void> crateApiRemoveBookmark({
    required MangaSource source,
    required String mangaId,
  });

  Future<void> crateApiSaveHistory({
    required MangaSource source,
    required String mangaId,
    required String mangaTitle,
    required String chapterPath,
    required String chapterTitle,
    required String thumbnail,
    required int lastPage,
  });

  Future<List<MangaSummary>> crateApiSearchManga({
    required MangaSource source,
    required String query,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KomikindoScraper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KomikindoScraper;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KomikindoScraperPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KomikuScraper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KomikuScraper;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KomikuScraperPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<ChapterPages> crateApiKomikindoKomikindoScraperGetChapterPages({
    required KomikindoScraper that,
    required String chapterPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
            that,
            serializer,
          );
          sse_encode_String(chapterPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_pages,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikindoKomikindoScraperGetChapterPagesConstMeta,
        argValues: [that, chapterPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiKomikindoKomikindoScraperGetChapterPagesConstMeta =>
      const TaskConstMeta(
        debugName: "KomikindoScraper_get_chapter_pages",
        argNames: ["that", "chapterPath"],
      );

  @override
  Future<List<MangaSummary>> crateApiKomikindoKomikindoScraperGetLatestManga({
    required KomikindoScraper that,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
            that,
            serializer,
          );
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikindoKomikindoScraperGetLatestMangaConstMeta,
        argValues: [that, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikindoKomikindoScraperGetLatestMangaConstMeta =>
      const TaskConstMeta(
        debugName: "KomikindoScraper_get_latest_manga",
        argNames: ["that", "page"],
      );

  @override
  Future<MangaDetail> crateApiKomikindoKomikindoScraperGetMangaDetail({
    required KomikindoScraper that,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
            that,
            serializer,
          );
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_manga_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikindoKomikindoScraperGetMangaDetailConstMeta,
        argValues: [that, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikindoKomikindoScraperGetMangaDetailConstMeta =>
      const TaskConstMeta(
        debugName: "KomikindoScraper_get_manga_detail",
        argNames: ["that", "mangaId"],
      );

  @override
  Future<KomikindoScraper> crateApiKomikindoKomikindoScraperNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKomikindoKomikindoScraperNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikindoKomikindoScraperNewConstMeta =>
      const TaskConstMeta(debugName: "KomikindoScraper_new", argNames: []);

  @override
  Future<List<MangaSummary>> crateApiKomikindoKomikindoScraperSearchManga({
    required KomikindoScraper that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikindoKomikindoScraperSearchMangaConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikindoKomikindoScraperSearchMangaConstMeta =>
      const TaskConstMeta(
        debugName: "KomikindoScraper_search_manga",
        argNames: ["that", "query"],
      );

  @override
  Future<ChapterPages> crateApiKomikuKomikuScraperGetChapterPages({
    required KomikuScraper that,
    required String chapterPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
            that,
            serializer,
          );
          sse_encode_String(chapterPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_pages,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikuKomikuScraperGetChapterPagesConstMeta,
        argValues: [that, chapterPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikuKomikuScraperGetChapterPagesConstMeta =>
      const TaskConstMeta(
        debugName: "KomikuScraper_get_chapter_pages",
        argNames: ["that", "chapterPath"],
      );

  @override
  Future<List<MangaSummary>> crateApiKomikuKomikuScraperGetLatestManga({
    required KomikuScraper that,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
            that,
            serializer,
          );
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikuKomikuScraperGetLatestMangaConstMeta,
        argValues: [that, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikuKomikuScraperGetLatestMangaConstMeta =>
      const TaskConstMeta(
        debugName: "KomikuScraper_get_latest_manga",
        argNames: ["that", "page"],
      );

  @override
  Future<MangaDetail> crateApiKomikuKomikuScraperGetMangaDetail({
    required KomikuScraper that,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
            that,
            serializer,
          );
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_manga_detail,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikuKomikuScraperGetMangaDetailConstMeta,
        argValues: [that, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikuKomikuScraperGetMangaDetailConstMeta =>
      const TaskConstMeta(
        debugName: "KomikuScraper_get_manga_detail",
        argNames: ["that", "mangaId"],
      );

  @override
  Future<KomikuScraper> crateApiKomikuKomikuScraperNew() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiKomikuKomikuScraperNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikuKomikuScraperNewConstMeta =>
      const TaskConstMeta(debugName: "KomikuScraper_new", argNames: []);

  @override
  Future<List<MangaSummary>> crateApiKomikuKomikuScraperSearchManga({
    required KomikuScraper that,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
            that,
            serializer,
          );
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiKomikuKomikuScraperSearchMangaConstMeta,
        argValues: [that, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiKomikuKomikuScraperSearchMangaConstMeta =>
      const TaskConstMeta(
        debugName: "KomikuScraper_search_manga",
        argNames: ["that", "query"],
      );

  @override
  Future<void> crateApiAddBookmark({
    required MangaSource source,
    required String mangaId,
    required String title,
    required String thumbnail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(thumbnail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAddBookmarkConstMeta,
        argValues: [source, mangaId, title, thumbnail],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAddBookmarkConstMeta => const TaskConstMeta(
    debugName: "add_bookmark",
    argNames: ["source", "mangaId", "title", "thumbnail"],
  );

  @override
  Future<void> crateApiClearHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiClearHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearHistoryConstMeta =>
      const TaskConstMeta(debugName: "clear_history", argNames: []);

  @override
  Future<void> crateApiDbDatabaseManagerAddBookmark({
    required MangaSource source,
    required String mangaId,
    required String title,
    required String thumbnail,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          sse_encode_String(title, serializer);
          sse_encode_String(thumbnail, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerAddBookmarkConstMeta,
        argValues: [source, mangaId, title, thumbnail],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerAddBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_add_bookmark",
        argNames: ["source", "mangaId", "title", "thumbnail"],
      );

  @override
  Future<void> crateApiDbDatabaseManagerClearHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerClearHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerClearHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_clear_history",
        argNames: [],
      );

  @override
  Future<List<BookmarkItem>> crateApiDbDatabaseManagerGetBookmarks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bookmark_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerGetBookmarksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerGetBookmarksConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_get_bookmarks",
        argNames: [],
      );

  @override
  Future<List<HistoryItem>> crateApiDbDatabaseManagerGetHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_item,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerGetHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerGetHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_get_history",
        argNames: [],
      );

  @override
  Future<void> crateApiDbDatabaseManagerInitDb({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerInitDbConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerInitDbConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_init_db",
        argNames: ["dbPath"],
      );

  @override
  Future<bool> crateApiDbDatabaseManagerIsBookmarked({
    required MangaSource source,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerIsBookmarkedConstMeta,
        argValues: [source, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerIsBookmarkedConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_is_bookmarked",
        argNames: ["source", "mangaId"],
      );

  @override
  Future<void> crateApiDbDatabaseManagerRemoveBookmark({
    required MangaSource source,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerRemoveBookmarkConstMeta,
        argValues: [source, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerRemoveBookmarkConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_remove_bookmark",
        argNames: ["source", "mangaId"],
      );

  @override
  Future<void> crateApiDbDatabaseManagerSaveHistory({
    required MangaSource source,
    required String mangaId,
    required String mangaTitle,
    required String chapterPath,
    required String chapterTitle,
    required String thumbnail,
    required int lastPage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          sse_encode_String(mangaTitle, serializer);
          sse_encode_String(chapterPath, serializer);
          sse_encode_String(chapterTitle, serializer);
          sse_encode_String(thumbnail, serializer);
          sse_encode_u_32(lastPage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiDbDatabaseManagerSaveHistoryConstMeta,
        argValues: [
          source,
          mangaId,
          mangaTitle,
          chapterPath,
          chapterTitle,
          thumbnail,
          lastPage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDbDatabaseManagerSaveHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "database_manager_save_history",
        argNames: [
          "source",
          "mangaId",
          "mangaTitle",
          "chapterPath",
          "chapterTitle",
          "thumbnail",
          "lastPage",
        ],
      );

  @override
  Future<List<BookmarkItem>> crateApiGetBookmarks() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bookmark_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetBookmarksConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBookmarksConstMeta =>
      const TaskConstMeta(debugName: "get_bookmarks", argNames: []);

  @override
  Future<ChapterPages> crateApiGetChapterPages({
    required MangaSource source,
    required String chapterPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(chapterPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_pages,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetChapterPagesConstMeta,
        argValues: [source, chapterPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetChapterPagesConstMeta => const TaskConstMeta(
    debugName: "get_chapter_pages",
    argNames: ["source", "chapterPath"],
  );

  @override
  Future<List<HistoryItem>> crateApiGetHistory() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_history_item,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetHistoryConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetHistoryConstMeta =>
      const TaskConstMeta(debugName: "get_history", argNames: []);

  @override
  Future<List<MangaSummary>> crateApiGetLatestManga({
    required MangaSource source,
    required int page,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_u_32(page, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetLatestMangaConstMeta,
        argValues: [source, page],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetLatestMangaConstMeta => const TaskConstMeta(
    debugName: "get_latest_manga",
    argNames: ["source", "page"],
  );

  @override
  Future<MangaDetail> crateApiGetMangaDetail({
    required MangaSource source,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_manga_detail,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetMangaDetailConstMeta,
        argValues: [source, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetMangaDetailConstMeta => const TaskConstMeta(
    debugName: "get_manga_detail",
    argNames: ["source", "mangaId"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 28,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> crateApiInitDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 29,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInitDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitDatabaseConstMeta =>
      const TaskConstMeta(debugName: "init_database", argNames: ["dbPath"]);

  @override
  Future<bool> crateApiIsBookmarked({
    required MangaSource source,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 30,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIsBookmarkedConstMeta,
        argValues: [source, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIsBookmarkedConstMeta => const TaskConstMeta(
    debugName: "is_bookmarked",
    argNames: ["source", "mangaId"],
  );

  @override
  Future<void> crateApiRemoveBookmark({
    required MangaSource source,
    required String mangaId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 31,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRemoveBookmarkConstMeta,
        argValues: [source, mangaId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRemoveBookmarkConstMeta => const TaskConstMeta(
    debugName: "remove_bookmark",
    argNames: ["source", "mangaId"],
  );

  @override
  Future<void> crateApiSaveHistory({
    required MangaSource source,
    required String mangaId,
    required String mangaTitle,
    required String chapterPath,
    required String chapterTitle,
    required String thumbnail,
    required int lastPage,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(mangaId, serializer);
          sse_encode_String(mangaTitle, serializer);
          sse_encode_String(chapterPath, serializer);
          sse_encode_String(chapterTitle, serializer);
          sse_encode_String(thumbnail, serializer);
          sse_encode_u_32(lastPage, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 32,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveHistoryConstMeta,
        argValues: [
          source,
          mangaId,
          mangaTitle,
          chapterPath,
          chapterTitle,
          thumbnail,
          lastPage,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveHistoryConstMeta => const TaskConstMeta(
    debugName: "save_history",
    argNames: [
      "source",
      "mangaId",
      "mangaTitle",
      "chapterPath",
      "chapterTitle",
      "thumbnail",
      "lastPage",
    ],
  );

  @override
  Future<List<MangaSummary>> crateApiSearchManga({
    required MangaSource source,
    required String query,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_manga_source(source, serializer);
          sse_encode_String(query, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_manga_summary,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSearchMangaConstMeta,
        argValues: [source, query],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSearchMangaConstMeta => const TaskConstMeta(
    debugName: "search_manga",
    argNames: ["source", "query"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KomikindoScraper => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KomikindoScraper => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_KomikuScraper => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_KomikuScraper => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  KomikindoScraper
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KomikuScraper
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KomikindoScraper
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KomikuScraper
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KomikindoScraper
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  KomikuScraper
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BookmarkItem dco_decode_bookmark_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BookmarkItem(
      mangaId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      thumbnail: dco_decode_String(arr[2]),
      source: dco_decode_manga_source(arr[3]),
      createdAt: dco_decode_i_64(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChapterItem(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      releaseDate: dco_decode_String(arr[2]),
      urlPath: dco_decode_String(arr[3]),
    );
  }

  @protected
  ChapterPages dco_decode_chapter_pages(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChapterPages(
      chapterId: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      images: dco_decode_list_String(arr[2]),
    );
  }

  @protected
  DatabaseManager dco_decode_database_manager(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.isNotEmpty)
      throw Exception('unexpected arr length: expect 0 but see ${arr.length}');
    return DatabaseManager();
  }

  @protected
  HistoryItem dco_decode_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return HistoryItem(
      mangaId: dco_decode_String(arr[0]),
      mangaTitle: dco_decode_String(arr[1]),
      chapterPath: dco_decode_String(arr[2]),
      chapterTitle: dco_decode_String(arr[3]),
      thumbnail: dco_decode_String(arr[4]),
      source: dco_decode_manga_source(arr[5]),
      lastPage: dco_decode_u_32(arr[6]),
      updatedAt: dco_decode_i_64(arr[7]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<BookmarkItem> dco_decode_list_bookmark_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bookmark_item).toList();
  }

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_item).toList();
  }

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_history_item).toList();
  }

  @protected
  List<MangaSummary> dco_decode_list_manga_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_manga_summary).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MangaDetail dco_decode_manga_detail(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return MangaDetail(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      alternativeTitle: dco_decode_String(arr[2]),
      thumbnail: dco_decode_String(arr[3]),
      author: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
      rating: dco_decode_String(arr[6]),
      synopsis: dco_decode_String(arr[7]),
      genres: dco_decode_list_String(arr[8]),
      chapters: dco_decode_list_chapter_item(arr[9]),
    );
  }

  @protected
  MangaSource dco_decode_manga_source(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return MangaSource.values[raw as int];
  }

  @protected
  MangaSummary dco_decode_manga_summary(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MangaSummary(
      id: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      thumbnail: dco_decode_String(arr[2]),
      latestChapter: dco_decode_String(arr[3]),
      typeName: dco_decode_String(arr[4]),
      description: dco_decode_String(arr[5]),
      source: dco_decode_manga_source(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  KomikindoScraper
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KomikuScraper
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KomikindoScraper
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KomikuScraper
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KomikindoScraper
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikindoScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  KomikuScraper
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return KomikuScraperImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BookmarkItem sse_decode_bookmark_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mangaId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_String(deserializer);
    var var_source = sse_decode_manga_source(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    return BookmarkItem(
      mangaId: var_mangaId,
      title: var_title,
      thumbnail: var_thumbnail,
      source: var_source,
      createdAt: var_createdAt,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_releaseDate = sse_decode_String(deserializer);
    var var_urlPath = sse_decode_String(deserializer);
    return ChapterItem(
      id: var_id,
      title: var_title,
      releaseDate: var_releaseDate,
      urlPath: var_urlPath,
    );
  }

  @protected
  ChapterPages sse_decode_chapter_pages(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chapterId = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_images = sse_decode_list_String(deserializer);
    return ChapterPages(
      chapterId: var_chapterId,
      title: var_title,
      images: var_images,
    );
  }

  @protected
  DatabaseManager sse_decode_database_manager(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DatabaseManager();
  }

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mangaId = sse_decode_String(deserializer);
    var var_mangaTitle = sse_decode_String(deserializer);
    var var_chapterPath = sse_decode_String(deserializer);
    var var_chapterTitle = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_String(deserializer);
    var var_source = sse_decode_manga_source(deserializer);
    var var_lastPage = sse_decode_u_32(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    return HistoryItem(
      mangaId: var_mangaId,
      mangaTitle: var_mangaTitle,
      chapterPath: var_chapterPath,
      chapterTitle: var_chapterTitle,
      thumbnail: var_thumbnail,
      source: var_source,
      lastPage: var_lastPage,
      updatedAt: var_updatedAt,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<BookmarkItem> sse_decode_list_bookmark_item(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BookmarkItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bookmark_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HistoryItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_history_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<MangaSummary> sse_decode_list_manga_summary(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MangaSummary>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_manga_summary(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MangaDetail sse_decode_manga_detail(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_alternativeTitle = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_rating = sse_decode_String(deserializer);
    var var_synopsis = sse_decode_String(deserializer);
    var var_genres = sse_decode_list_String(deserializer);
    var var_chapters = sse_decode_list_chapter_item(deserializer);
    return MangaDetail(
      id: var_id,
      title: var_title,
      alternativeTitle: var_alternativeTitle,
      thumbnail: var_thumbnail,
      author: var_author,
      status: var_status,
      rating: var_rating,
      synopsis: var_synopsis,
      genres: var_genres,
      chapters: var_chapters,
    );
  }

  @protected
  MangaSource sse_decode_manga_source(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return MangaSource.values[inner];
  }

  @protected
  MangaSummary sse_decode_manga_summary(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_thumbnail = sse_decode_String(deserializer);
    var var_latestChapter = sse_decode_String(deserializer);
    var var_typeName = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    var var_source = sse_decode_manga_source(deserializer);
    return MangaSummary(
      id: var_id,
      title: var_title,
      thumbnail: var_thumbnail,
      latestChapter: var_latestChapter,
      typeName: var_typeName,
      description: var_description,
      source: var_source,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikindoScraperImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikuScraperImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikindoScraperImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikuScraperImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikindoScraperImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as KomikuScraperImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bookmark_item(BookmarkItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mangaId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.thumbnail, serializer);
    sse_encode_manga_source(self.source, serializer);
    sse_encode_i_64(self.createdAt, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.releaseDate, serializer);
    sse_encode_String(self.urlPath, serializer);
  }

  @protected
  void sse_encode_chapter_pages(ChapterPages self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chapterId, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_list_String(self.images, serializer);
  }

  @protected
  void sse_encode_database_manager(
    DatabaseManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mangaId, serializer);
    sse_encode_String(self.mangaTitle, serializer);
    sse_encode_String(self.chapterPath, serializer);
    sse_encode_String(self.chapterTitle, serializer);
    sse_encode_String(self.thumbnail, serializer);
    sse_encode_manga_source(self.source, serializer);
    sse_encode_u_32(self.lastPage, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bookmark_item(
    List<BookmarkItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bookmark_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_history_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_manga_summary(
    List<MangaSummary> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_manga_summary(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_manga_detail(MangaDetail self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.alternativeTitle, serializer);
    sse_encode_String(self.thumbnail, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_String(self.rating, serializer);
    sse_encode_String(self.synopsis, serializer);
    sse_encode_list_String(self.genres, serializer);
    sse_encode_list_chapter_item(self.chapters, serializer);
  }

  @protected
  void sse_encode_manga_source(MangaSource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_manga_summary(MangaSummary self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.thumbnail, serializer);
    sse_encode_String(self.latestChapter, serializer);
    sse_encode_String(self.typeName, serializer);
    sse_encode_String(self.description, serializer);
    sse_encode_manga_source(self.source, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class KomikindoScraperImpl extends RustOpaque implements KomikindoScraper {
  // Not to be used by end users
  KomikindoScraperImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KomikindoScraperImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KomikindoScraper,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KomikindoScraper,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_KomikindoScraperPtr,
  );

  Future<ChapterPages> getChapterPages({required String chapterPath}) =>
      RustLib.instance.api.crateApiKomikindoKomikindoScraperGetChapterPages(
        that: this,
        chapterPath: chapterPath,
      );

  Future<List<MangaSummary>> getLatestManga({required int page}) => RustLib
      .instance
      .api
      .crateApiKomikindoKomikindoScraperGetLatestManga(that: this, page: page);

  Future<MangaDetail> getMangaDetail({required String mangaId}) =>
      RustLib.instance.api.crateApiKomikindoKomikindoScraperGetMangaDetail(
        that: this,
        mangaId: mangaId,
      );

  Future<List<MangaSummary>> searchManga({required String query}) => RustLib
      .instance
      .api
      .crateApiKomikindoKomikindoScraperSearchManga(that: this, query: query);
}

@sealed
class KomikuScraperImpl extends RustOpaque implements KomikuScraper {
  // Not to be used by end users
  KomikuScraperImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  KomikuScraperImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_KomikuScraper,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_KomikuScraper,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_KomikuScraperPtr,
  );

  Future<ChapterPages> getChapterPages({required String chapterPath}) =>
      RustLib.instance.api.crateApiKomikuKomikuScraperGetChapterPages(
        that: this,
        chapterPath: chapterPath,
      );

  Future<List<MangaSummary>> getLatestManga({required int page}) => RustLib
      .instance
      .api
      .crateApiKomikuKomikuScraperGetLatestManga(that: this, page: page);

  Future<MangaDetail> getMangaDetail({required String mangaId}) => RustLib
      .instance
      .api
      .crateApiKomikuKomikuScraperGetMangaDetail(that: this, mangaId: mangaId);

  Future<List<MangaSummary>> searchManga({required String query}) => RustLib
      .instance
      .api
      .crateApiKomikuKomikuScraperSearchManga(that: this, query: query);
}
