// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/db.dart';
import 'api/komikindo.dart';
import 'api/komiku.dart';
import 'api/models.dart';
import 'api/simple.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KomikindoScraperPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_KomikuScraperPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  KomikindoScraper
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  );

  @protected
  KomikuScraper
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  );

  @protected
  KomikindoScraper
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  );

  @protected
  KomikuScraper
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  );

  @protected
  KomikindoScraper
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    dynamic raw,
  );

  @protected
  KomikuScraper
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BookmarkItem dco_decode_bookmark_item(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DownloadedChapter dco_decode_box_autoadd_downloaded_chapter(dynamic raw);

  @protected
  ChapterItem dco_decode_chapter_item(dynamic raw);

  @protected
  ChapterPages dco_decode_chapter_pages(dynamic raw);

  @protected
  DatabaseManager dco_decode_database_manager(dynamic raw);

  @protected
  DownloadedChapter dco_decode_downloaded_chapter(dynamic raw);

  @protected
  HistoryItem dco_decode_history_item(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<BookmarkItem> dco_decode_list_bookmark_item(dynamic raw);

  @protected
  List<ChapterItem> dco_decode_list_chapter_item(dynamic raw);

  @protected
  List<DownloadedChapter> dco_decode_list_downloaded_chapter(dynamic raw);

  @protected
  List<HistoryItem> dco_decode_list_history_item(dynamic raw);

  @protected
  List<MangaSummary> dco_decode_list_manga_summary(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  MangaDetail dco_decode_manga_detail(dynamic raw);

  @protected
  MangaSource dco_decode_manga_source(dynamic raw);

  @protected
  MangaSummary dco_decode_manga_summary(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  KomikindoScraper
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  );

  @protected
  KomikuScraper
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  );

  @protected
  KomikindoScraper
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  );

  @protected
  KomikuScraper
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  );

  @protected
  KomikindoScraper
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    SseDeserializer deserializer,
  );

  @protected
  KomikuScraper
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BookmarkItem sse_decode_bookmark_item(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DownloadedChapter sse_decode_box_autoadd_downloaded_chapter(
    SseDeserializer deserializer,
  );

  @protected
  ChapterItem sse_decode_chapter_item(SseDeserializer deserializer);

  @protected
  ChapterPages sse_decode_chapter_pages(SseDeserializer deserializer);

  @protected
  DatabaseManager sse_decode_database_manager(SseDeserializer deserializer);

  @protected
  DownloadedChapter sse_decode_downloaded_chapter(SseDeserializer deserializer);

  @protected
  HistoryItem sse_decode_history_item(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<BookmarkItem> sse_decode_list_bookmark_item(
    SseDeserializer deserializer,
  );

  @protected
  List<ChapterItem> sse_decode_list_chapter_item(SseDeserializer deserializer);

  @protected
  List<DownloadedChapter> sse_decode_list_downloaded_chapter(
    SseDeserializer deserializer,
  );

  @protected
  List<HistoryItem> sse_decode_list_history_item(SseDeserializer deserializer);

  @protected
  List<MangaSummary> sse_decode_list_manga_summary(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  MangaDetail sse_decode_manga_detail(SseDeserializer deserializer);

  @protected
  MangaSource sse_decode_manga_source(SseDeserializer deserializer);

  @protected
  MangaSummary sse_decode_manga_summary(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    KomikindoScraper self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    KomikuScraper self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bookmark_item(BookmarkItem self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_downloaded_chapter(
    DownloadedChapter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_item(ChapterItem self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_pages(ChapterPages self, SseSerializer serializer);

  @protected
  void sse_encode_database_manager(
    DatabaseManager self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_downloaded_chapter(
    DownloadedChapter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_history_item(HistoryItem self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_bookmark_item(
    List<BookmarkItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_chapter_item(
    List<ChapterItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_downloaded_chapter(
    List<DownloadedChapter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_history_item(
    List<HistoryItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_manga_summary(
    List<MangaSummary> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_manga_detail(MangaDetail self, SseSerializer serializer);

  @protected
  void sse_encode_manga_source(MangaSource self, SseSerializer serializer);

  @protected
  void sse_encode_manga_summary(MangaSummary self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikindoScraper(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerKomikuScraper(
    int ptr,
  );
}
