// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `current_timestamp`, `get_conn`, `source_to_string`, `string_to_source`

class DatabaseManager {
  const DatabaseManager();

  static Future<void> addBookmark({
    required MangaSource source,
    required String mangaId,
    required String title,
    required String thumbnail,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerAddBookmark(
    source: source,
    mangaId: mangaId,
    title: title,
    thumbnail: thumbnail,
  );

  static Future<void> clearHistory() =>
      RustLib.instance.api.crateApiDbDatabaseManagerClearHistory();

  static Future<String> deleteDownloadedChapter({
    required MangaSource source,
    required String chapterId,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerDeleteDownloadedChapter(
    source: source,
    chapterId: chapterId,
  );

  static Future<List<BookmarkItem>> getBookmarks() =>
      RustLib.instance.api.crateApiDbDatabaseManagerGetBookmarks();

  static Future<List<DownloadedChapter>> getDownloadedChapters() =>
      RustLib.instance.api.crateApiDbDatabaseManagerGetDownloadedChapters();

  static Future<List<HistoryItem>> getHistory() =>
      RustLib.instance.api.crateApiDbDatabaseManagerGetHistory();

  static Future<void> initDb({required String dbPath}) =>
      RustLib.instance.api.crateApiDbDatabaseManagerInitDb(dbPath: dbPath);

  static Future<bool> isBookmarked({
    required MangaSource source,
    required String mangaId,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerIsBookmarked(
    source: source,
    mangaId: mangaId,
  );

  static Future<bool> isChapterDownloaded({
    required MangaSource source,
    required String chapterId,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerIsChapterDownloaded(
    source: source,
    chapterId: chapterId,
  );

  static Future<void> removeBookmark({
    required MangaSource source,
    required String mangaId,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerRemoveBookmark(
    source: source,
    mangaId: mangaId,
  );

  static Future<void> saveDownloadedChapter({
    required DownloadedChapter chapter,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerSaveDownloadedChapter(
    chapter: chapter,
  );

  static Future<void> saveHistory({
    required MangaSource source,
    required String mangaId,
    required String mangaTitle,
    required String chapterPath,
    required String chapterTitle,
    required String thumbnail,
    required int lastPage,
  }) => RustLib.instance.api.crateApiDbDatabaseManagerSaveHistory(
    source: source,
    mangaId: mangaId,
    mangaTitle: mangaTitle,
    chapterPath: chapterPath,
    chapterTitle: chapterTitle,
    thumbnail: thumbnail,
    lastPage: lastPage,
  );

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DatabaseManager && runtimeType == other.runtimeType;
}
