// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'models.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<KomikindoScraper>>
abstract class KomikindoScraper implements RustOpaqueInterface {
  Future<ChapterPages> getChapterPages({required String chapterPath});

  Future<List<MangaSummary>> getLatestManga({required int page});

  Future<MangaDetail> getMangaDetail({required String mangaId});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<KomikindoScraper> newInstance() =>
      RustLib.instance.api.crateApiKomikindoKomikindoScraperNew();

  Future<List<MangaSummary>> searchManga({required String query});
}
