// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class BookmarkItem {
  final String mangaId;
  final String title;
  final String thumbnail;
  final MangaSource source;
  final PlatformInt64 createdAt;

  const BookmarkItem({
    required this.mangaId,
    required this.title,
    required this.thumbnail,
    required this.source,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      title.hashCode ^
      thumbnail.hashCode ^
      source.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookmarkItem &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          title == other.title &&
          thumbnail == other.thumbnail &&
          source == other.source &&
          createdAt == other.createdAt;
}

class ChapterItem {
  final String id;
  final String title;
  final String releaseDate;
  final String urlPath;

  const ChapterItem({
    required this.id,
    required this.title,
    required this.releaseDate,
    required this.urlPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^ title.hashCode ^ releaseDate.hashCode ^ urlPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          releaseDate == other.releaseDate &&
          urlPath == other.urlPath;
}

class ChapterPages {
  final String chapterId;
  final String title;
  final List<String> images;

  const ChapterPages({
    required this.chapterId,
    required this.title,
    required this.images,
  });

  @override
  int get hashCode => chapterId.hashCode ^ title.hashCode ^ images.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterPages &&
          runtimeType == other.runtimeType &&
          chapterId == other.chapterId &&
          title == other.title &&
          images == other.images;
}

class HistoryItem {
  final String mangaId;
  final String mangaTitle;
  final String chapterPath;
  final String chapterTitle;
  final String thumbnail;
  final MangaSource source;
  final int lastPage;
  final PlatformInt64 updatedAt;

  const HistoryItem({
    required this.mangaId,
    required this.mangaTitle,
    required this.chapterPath,
    required this.chapterTitle,
    required this.thumbnail,
    required this.source,
    required this.lastPage,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      mangaId.hashCode ^
      mangaTitle.hashCode ^
      chapterPath.hashCode ^
      chapterTitle.hashCode ^
      thumbnail.hashCode ^
      source.hashCode ^
      lastPage.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryItem &&
          runtimeType == other.runtimeType &&
          mangaId == other.mangaId &&
          mangaTitle == other.mangaTitle &&
          chapterPath == other.chapterPath &&
          chapterTitle == other.chapterTitle &&
          thumbnail == other.thumbnail &&
          source == other.source &&
          lastPage == other.lastPage &&
          updatedAt == other.updatedAt;
}

class MangaDetail {
  final String id;
  final String title;
  final String alternativeTitle;
  final String thumbnail;
  final String author;
  final String status;
  final String rating;
  final String synopsis;
  final List<String> genres;
  final List<ChapterItem> chapters;

  const MangaDetail({
    required this.id,
    required this.title,
    required this.alternativeTitle,
    required this.thumbnail,
    required this.author,
    required this.status,
    required this.rating,
    required this.synopsis,
    required this.genres,
    required this.chapters,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      alternativeTitle.hashCode ^
      thumbnail.hashCode ^
      author.hashCode ^
      status.hashCode ^
      rating.hashCode ^
      synopsis.hashCode ^
      genres.hashCode ^
      chapters.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaDetail &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          alternativeTitle == other.alternativeTitle &&
          thumbnail == other.thumbnail &&
          author == other.author &&
          status == other.status &&
          rating == other.rating &&
          synopsis == other.synopsis &&
          genres == other.genres &&
          chapters == other.chapters;
}

enum MangaSource { komiku, komikindo }

class MangaSummary {
  final String id;
  final String title;
  final String thumbnail;
  final String latestChapter;
  final String typeName;
  final String description;
  final MangaSource source;

  const MangaSummary({
    required this.id,
    required this.title,
    required this.thumbnail,
    required this.latestChapter,
    required this.typeName,
    required this.description,
    required this.source,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      thumbnail.hashCode ^
      latestChapter.hashCode ^
      typeName.hashCode ^
      description.hashCode ^
      source.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MangaSummary &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          thumbnail == other.thumbnail &&
          latestChapter == other.latestChapter &&
          typeName == other.typeName &&
          description == other.description &&
          source == other.source;
}
